variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3.8.2-jdk-11-slim

stages:
  - compile
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

unittests-job:
  stage: test

  before_script:
    - apt-get update && apt-get install -y make

  script:
    - echo "Running all unit tests"
    - make clean
    - mvn verify -DskipTests
    - make run_all_non_server_unittests

ref-server-default-world-accpeptance-tests-job:
  stage: test

  before_script:
    - apt-get update && apt-get install -y make

  script:
    - make clean
    - mvn verify -DskipTests
    - make test_reference_server_default

