variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  
default:
  image: maven:3.8.2-jdk-11-slim

  before_script:
    - apt-get update && apt install make

  cache:
    paths:
      - .m2/repository
      - target
      - Server/target
      - Client/target

unittests-job:
  stage: test

  script:
    - echo "Running all unit tests"
    - mvn verify -DskipTests
    - make run_all_non_server_unittests

ref-server-default-world-accpeptance-tests-job:
  stage: test

  before_script:
    - make run_reference_server_jar

  script:
    - mvn verify -DskipTests
    - make run_1x1_acceptance_tests
    - make stop_reference_server

uss-victory-default-world-accpeptance-tests-job:
  stage: test

  before_script:
    - make development_build
    - make run_uss_victory_server_jar

  script:
    - mvn verify -DskipTests
    - make run_1x1_acceptance_tests
    - make stop_uss_victory_server

uss-victory-2x2-world-acceptance-tests-job:
  stage: test

  before_script:
    - make development_build
    - make run_dev_build_2x2_world

  script:
    - mvn verify -DskipTests
    - make run_2x2_acceptance_tests
    - make stop_uss_victory_server
