

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.8.2-jdk-11-slim

  before_script:
    - apt-get update && apt install make
    - apt-get install docker.io -y
    - docker image prune
    - make add_eodsql
    - mvn clean install -U -DskipTests
    - mvn verify -DskipTests
    - make development_build

unittests-job:
  stage: test

  script:
    - echo "Running all unit tests"
    - make run_all_non_server_unittests

uss-victory-default-world-accpeptance-tests-job:
  stage: test

  script:
    - make run_uss_victory_server_jar
    - make run_1x1_acceptance_tests
  after_script:
    - make stop_uss_victory_server

uss-victory-2x2-world-acceptance-tests-job:
  stage: test

  script:
    - make run_dev_build_2x2_world
    - make run_2x2_acceptance_tests
  after_script:
    - make stop_uss_victory_server

uss-victory-obstacle-1,1-2x2-world-acceptance-tests-job:
  stage: test

  script:
    - make run_dev_build_1,1_obstacle_2x2_world
    - make run_2x2_1,1_obstacle_acceptance_tests
  after_script:
    - make stop_uss_victory_server

compile:
  stage: build

  script:
    - make compile

uss-victory-api-server-acceptance-tests:
  stage: test

  script:
    - make run_api_acceptance_tests

release_multiserver:
  
  stage: deploy

  script:
    - docker images
    - make release_build
    - docker login -u sluthang -p QBytvCSqKQ1uXbPefsNW gitlab.wethinkco.de:5050
    - docker build -t uss-victory-server:0.4.2 -f docker/socket-server/Dockerfile .
    - docker tag uss-victory-server:0.4.2 gitlab.wethinkco.de:5050/sprocopo/uss-victory
    - docker push gitlab.wethinkco.de:5050/sprocopo/uss-victory

release_api:

  stage: deploy

  script:
    - make api_release_build
    - docker login -u sluthang -p QBytvCSqKQ1uXbPefsNW gitlab.wethinkco.de:5050
    - docker build -t uss-victory-api-server:1.3 -f docker/api/Dockerfile .
    - docker tag uss-victory-api-server:1.3 gitlab.wethinkco.de:5050/sprocopo/uss-victory
    - docker push gitlab.wethinkco.de:5050/sprocopo/uss-victory